

spring:

  # security优先级设置
  security:
    filter:
      order: -100
  # 连接MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.222.46:3306/yatian?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Jk#020034

  # Spring Mail 邮箱相关配置
  mail:
    host: smtp.qq.com
    port: 465
    username: 2083717185@qq.com
    password: udkxrbsqvmgwdifg
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: x-utf-16le-bom

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 47.113.222.46:9300

  # KafkaProperties
  kafka:
    bootstrap-servers: 47.113.222.46:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000

  # redis
  redis:
    host: 47.113.222.46
    port: 6379
    # password: jk18889903808


# JWT
token:
  # JWT私钥
  privateKey: 'fdasfgdsagaxgsregdfdjyghjfhebfdgwe45ygrfbsdfshfdsag'
  # token生成时间超过yangToken变oldToken 访问刷新 (后期为了用户被盗号后必须更新token可能会废用
  # 一小时
  yangToken: 3600000
  # 六小时
  # token过期时长 一秒=1000
  oldToken: 21600000

community:
  path:
    # 开发用
    domain: http://localhost:8088
    domain_vue: yatian.joing7.com
    # upload: J:/javaProject/data/upload

# Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.joking.yatian.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

# ServerProperties
server:
  # 端口
  port: 8088
  servlet:
    context-path:


# caffeine
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180

# 配置wkhtmltoimage
wk:
  image:
    command: wkhtmltoimage
    storage: ./wkimage/data

# qiniu
qiniu:
  key:
    access: zGvmrQUw250mt5AgPShm1izDKll9o4b-tG_nnY38
    secret: Vnc3HSTuvPmwGZb0bRPbnn1CSMmr0UYeRwjoESfK
  bucket:
    header:
      name: yatian-pic-header
      url: yatian-pic-header.joking7.com

    share:
      name: yatian-pic-share
      url: yatian-pic-share.joking7.com

# logback
logging:
  cofig: classpath:logback-spring-${spring.profiles.active}.xml
